### ISSUE TITLE
skip retries on XDMP-SPECIALPROP

### ISSUE THREAD

**Issue by mblakele** [MarkLogic-Attic/xqsync#6]
The retries are not needed since `XDMP-SPECIALPROP` is not a transient error. We could also use some docs on why `XDMP-SPECIALPROP` happens.

```
2013-12-16 10:00:13.286 WARNING: error writing document (/tests/229), will retry 4 more times.
2013-12-16 10:00:13.549 WARNING: error writing document (/tests/229), will retry 3 more times.
2013-12-16 10:00:14.059 WARNING: error writing document (/tests/229), will retry 2 more times.
2013-12-16 10:00:15.070 WARNING: error writing document (/tests/229), will retry 1 more times.
2013-12-16 10:00:17.083 SEVERE: sync failed for: /tests/229
2013-12-16 10:00:17.083 WARNING: error in input package /Users/mblakele/backup/tests/tests-000.zip
2013-12-16 10:00:17.084 SEVERE: non-fatal
java.util.concurrent.ExecutionException: com.marklogic.ps.xqsync.SyncException: write failed, all retries exhausted for /tests/229
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
    at java.util.concurrent.FutureTask.get(FutureTask.java:83)
    at com.marklogic.ps.xqsync.Monitor.monitor(Monitor.java:154)
    at com.marklogic.ps.xqsync.Monitor.run(Monitor.java:87)
Caused by: com.marklogic.ps.xqsync.SyncException: write failed, all retries exhausted for /tests/229
    at com.marklogic.ps.xqsync.SessionWriter.write(SessionWriter.java:305)
    at com.marklogic.ps.xqsync.XQSyncDocument.write(XQSyncDocument.java:164)
    at com.marklogic.ps.xqsync.XQSyncDocument.sync(XQSyncDocument.java:128)
    at com.marklogic.ps.xqsync.CallableSync.call(CallableSync.java:87)
    at com.marklogic.ps.xqsync.CallableSync.call(CallableSync.java:32)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
Caused by: com.marklogic.xcc.exceptions.XQueryException: XDMP-SPECIALPROP: xdmp:document-set-properties("/tests/229", <prop:last-modified xmlns:prop="http://marklogic.com/xdmp/property">2013-12-08T15:40:38-08:00</prop:last-modified>) -- Cannot update server-maintained properties
 [Session: user=q, cb=test [ContentSource: user=q, cb=test [provider: address=localhost/127.0.0.1:9000, pool=0/64]]]
 [Client: XCC/6.0-1, Server: XDBC/7.0-1]
on line 4
```

**Comment by vladistan** [comment]
Not sure if this project still alive.  Here is the fix for the issue  https://github.com/Coveros/xqsync/pull/1  

Can't submit it here until you guys merge the reset of @Coveros changes in.
